= Team 43 - Project Description

== Introducción

El mundo actual y las tecnologías existentes permiten que se tengan grandes volúmenes de información sobre lo que sucede en el mundo (redes sociales, medios de comunicación y datos de entidades oficiales).
La rápida divulgación de las noticias, en especial aquellas relacionadas con el crimen en distintas plataformas, incrementan la percepción de inseguridad a pesar de que los datos indiquen lo contrario.

== Descripción del Problema

Cali no es ajena a esta problemática global.
Una encuesta de percepción y victimización hecha en 2018 para la Secretaría de Seguridad y Justicia de Cali halló que el 51 % de los encuestados se siente inseguro en la ciudad y el 16 % se siente muy inseguro, para un total de 67 % con percepción negativa de seguridad.
Solo el 20% se siente seguro y el 13 % medianamente seguro, mientras la Policía Metropolitana de Cali presenta sus cifras de reducción en delitos de alto impacto.

Todo lo anterior, afecta la calidad de vida de los Caleños, por lo que el objetivo de este proyecto es que las personas tengan una fuente de información confiable, analizada y amigable para disminuir la brecha entre percepción vs realidad sobre la seguridad de la ciudad.

== Relevancia

Esta problemática es relevante porque:

* Una percepción negativa sobre la seguridad en Cali genera baja calidad de vida para los ciudadanos, poca atracción al turismo e inversión local y extranjera.
* La desconfianza sobre los datos publicados por el gobierno, desincentiva la participación y conciencia ciudadana.
* La desinformación no permite que las estrategias desarrolladas para disminuir la inseguridad en la ciudad tengan los resultados esperados.
* Los actores responsables en llevar a cabo estrategias de mejoramiento en seguridad pueden sentirse desmotivados ante las continuas percepciones negativas de la ciudadanía.
* El análisis de los datos abiertos de entidades públicas para identificar información relevante, permite al gobierno local y a los entes de orden público tomar decisiones acertadas que permitan mejorar la calidad de vida de los ciudadanos. Esto se puede ver reflejado en el incremento de programas sociales, educativos y/o redistribución del control del orden público.

== Conjutos de Datos

* Registros de Homicidios y delitos del Departamento de Policía Nacional (*Policía Nacional*). Fuente: *Chispa*.
* Información demográfica del Departamento Administrativo Nacional de Estadística (*DANE*).
* Percepción de los ciudadanos respecto a múltiples factores socio económicos (*Cali Cómo vamos - ciudatos.com*): encuestas.
* Información del clima del Instituto de Hidrología, Meteorología y Estudios Ambientales (*IDEAM*).
* Programas sociales, festividades nacionales y locales, eventos especiales y periodos de alcaldías (*Alcaldía de Cali*).
