= Team 43 - Project Description

== Overview

The current world and the technology trends allow us to have large volumes of information about what is happening in the world (social networks, the media and data from official entities).
The rapid dissemination of news, especially related to crime on different platforms, increases the perception of insecurity despite the fact that the data specifies otherwise.

== Problem Description

Cali is no stranger to this global problem.
A perception and victimization survey carried out in 2018 for the Ministry of Security and Justice of Cali found that 51% of respondents feel insecure in the city and 16% feel very insecure, for a total of 67% with a negative perception of security.
Only 20% feel safe and 13% moderately safe, while the Cali Metropolitan Police presents their reduction figures for high-impact crimes.

All of this affects the life’s quality of Cali’s citizens, for that reason the objective of this project is that people have a trustworthy, analyzed and friendly source of information to decrease the gap between perception and reality about the security of the city.

== Relevance

This problem matters because:

* A negative perception of security in Cali generates low quality of life for citizens, as well as, low attraction from locals and foreigners to tourism and investment.
* Mistrust of the data published by the government discourages citizen participation and awareness.
* Disinformation does not allow the strategies developed to reduce insecurity in the city to have the expected results.
* The actors responsible for carrying out security improvement strategies may feel unmotivated by the continuous negative perceptions of citizens.
* The analysis of open data from public entities to identify relevant information, allows local government and law enforcement to make sound decisions that improve the quality of life of citizens. This can be seen reflected in the increase in social, educational and / or redistribution of public order control programs.

== Data Sets

* Homicides and criminal records from the National Police Department (*Policía Nacional*). Source: *Chispa*.
* Demographic information from the National Administrative Department of Statistics (*DANE*).
* Citizens' perception about multiple socio-economic factors (*Cali Cómo vamos - ciudatos.com*): surveys.
* Weather information from the Institute of Hydrology, Meteorology and Environmental Studies (*IDEAM*).
* Social programs, national and local holidays, festivals and special events, mayoral periods (*Alcaldía de Cali*).
