*Fecha:* 2020-06-04

*Hora:* 17:00

== Participantes

* Daniel Gaitan Forero
* Fabio Andrés Sánchez Bernal
* Jhon Alexander Parra Jiménez
* Jonathan Guevara Agudelo
* Luz Elena Thompson Pinzón
* Maria Camila Manrique Nuñez

== Agenda

. Tomar una decisión respecto al proyecto a ejecutar.
. Pasos siguientes.

== Ítem 1

Hasta la fecha no se ha obtenido respuesta por parte de los dos proyectos elegidos inicialmente, por lo que la opción más probable es la propuesta presentada por *Chispa*.

Se decide dar una espera hasta el viernes al final del día para que las entidades inicales nos den una respuesta, antes de tomar una decisión definitiva.

Respecto a la propuesta de *Chispa*, se identifica que puede ser un proyecto un poco abierto y ambicioso, por lo que se decide buscar una nueva reunión con un representante de *Chispa* para explorar otras problemáticas que hayan identificado.

== Pasos siguientes

. Hacer un nueva reunión el 2020-06-05 con alguno de los representantes de *Chispa* para explorar otras problemáticas.
