*Fecha:* 2020-05-28

*Hora:* 17:00

== Participantes

* Daniel Gaitan Forero
* Fabio Andrés Sánchez Bernal
* Jhon Alexander Parra Jiménez
* Jonathan Guevara Agudelo
* Luz Elena Thompson Pinzón
* Maria Camila Manrique Nuñez

== Agenda

. Elección final de los proyectos a trabajar, teniendo en cuenta los candidatos individuales y los argumentos de cada integrante.
. Pasos siguientes.

== Ítem 1

Cada miembro del equipo eligió uno de los proyectos como el mejor opcionado (calificación de 5) y realizó la sustentación de las razones para su elección (algunos ya lo habían hecho la sesión pasada).

De todas las calificaciones, se consideraron los siguientes 5 proyectos con mayor puntuación:

* Alcaldía de Copacabana
* EPM - 1
* FonTIC
* Agencia de Desarrollo Rural
* Latam Analytics

Sobre esta elección final, cada integrante asignó una valoración de 1 a 5 (sin repetición), para poder determinar los dos o tres proyectos a considerar (aquel con mayor puntuación).
De acuerdo con la votación, se llegó al siguiente listado defintivo:

. Alcaldía de Copacabana
. EPM - 1
. FonTIC

Se acordó contactar a los dos primeros proyectos, teniendo en cuenta las instrucciones de *Correlation One* y los TA's. En caso de no obtener ninguna respuesta, se procederá a contactar al tercero.

Para este primer contacto, se determinó crear un borrador del contenido del email para revisión de todos y poderlo enviar al día siguiente.

== Pasos Siguientes

. Crear borrador del email correspondiente al primer contacto con las dos primeras entidades seleccionadas.
. Envíar el email a los contactos listados de las entidades seleccionadas.
. Elaborar un conjunto de preguntas para las sesiones con las personas de contacto de cada proyecto.

== Actualización 2020-05-29

. Punto 1 de la sección *Pasos siguientes* fue ejecutado el 200-05-28.
. Punto 2 de la sección *Pasos siguientes* fue ejecutado el 200-05-29.
