*Fecha:* 2020-05-31

*Hora:* 15:30

== Participantes

* Daniel Gaitan Forero
* Fabio Andrés Sánchez Bernal
* Jhon Alexander Parra Jiménez
* Jonathan Guevara Agudelo
* Luz Elena Thompson Pinzón
* Maria Camila Manrique Nuñez
* Germán Camilo Alfonso Ruíz (Chispa)

== Agenda

. Reunión con el representante del proyecto https://chis.pa[*Chispa*] y conocer las propuestas disponibles.
. Pasos siguientes.

== Ítem 1

El representante de https://chis.pa[*Chispa*] realizó una breve descripción de la iniciativa, al igual que una descripción del perfil de sus integrantes.

De forma general, la iniciativa nace de tres amigos que buscan impactar positivamente la calidad de vida en Cali.
Esto, a través del análisis de los datos disponibles de forma abierta para que las personas y las diferentes entidades de la ciudad puedan tomar decisiones.
Actualmente cuentan con una plataforma de datos que va a ser lanzada  el miércoles 3 de junio para que pueda ser accedida por cualquiera.

La organización obtiene y hace una validación inicial de los datos entregados por la Policia Nacional respecto a diferentes delitos a nivel nacional.
Sobre estos datos han obtenido algunas estadísticas básicas, sin embargo, buscan que las personas puedan realizar procesos de análisis más profundos y que sean accesibles a todos.

Otros datos:

* Alianza con Datopian (CKAN).
* Buscan realizar la predicción de crimenes, homicidios, robos.
* La información disponible está detallada hasta nivel de barrio.
* Se tiene información de los últimos 10 años.
* Se busca complementar la información de la Policia Nacional con datos libres.
* https://datapico.com[*Data Pico*] es la empresa de uno de los socios de la organización.

== Pasos siguientes

. Hacer seguimiento a las comunicaciones enviadas a la *Alcaldía de Copabacaba* y *EPM*.
. Hacer un nueva reunión el 2020-06-04 para tomar una decisión respecto al proyecto a ejecutar.
