*Fecha:* 2020-05-30

*Hora:* 13:30

== Participantes

* Daniel Gaitan Forero
* Fabio Andrés Sánchez Bernal
* Jhon Alexander Parra Jiménez
* Jonathan Guevara Agudelo
* Luz Elena Thompson Pinzón
* Maria Camila Manrique Nuñez

== Agenda

. Revisar las inquietudes a plantear en la sesión con los TA's.
. Discutir las actividades que se deben iniciar para la ejecución del Practicum.
. Discutir proyectos alternativos por fuera del listado de Open Projects.
. Pasos siguientes.

== Ítem 1

Se generaron las siguientes preguntas:

. What are the important things to consider while meeting with the responsible from the entity's side?
+
*Respuesta:*

    * Conocer un poco más acerca de la entidad en forma general.
    * Discutir las expectactivas e intereses de ambas partes y que estén alineadas.
    * Preguntar todo lo posible acerca de la problemática y los datos.

. Are there any disavantages to have mostly categorical variables?
+
*Respuesta:*

    * Depende del alcance del proyecto, aunque no debería ser ningún inconveniente. Se deben buscar métodos que permitan trabajar con este tipo de datos (Análisis exploratorio, factorial, etc.).

. What area the expectations from the DS4A program regarding the practicum, in terms of the scope of the project, methods and the tools used?
+
*Respuesta:*

    * El principal objetivo es poder demostrar la capacidad de resolver un problema de Data Science desde cero.
    * No hay restricción en cuanto a las herramientas ni métodos usados.
    * Lo más importante es poder dar una solución al problema propuesto.

. We still don't have data from any of the selected projects, so, what would be a good starting point a this moment so we get the practicum moving?
+
*Respuesta:*

    * Entender bien el problema a abordar y comenzar a definir el alcance.
    * Reunión con los Data Owners para establecer el alcance y obtener acceso a los datos.

. Is there a methodology that you suggest to follow?
+
*Respuesta:*

    * Depende del tipo de problema.

.  Can we use third-parties components like Power BI, Tableau or free libraries for the visualization?
+
*Respuesta:*

    * Se da respuesta en la pregunta 3: no hay restricción en cuanto a las herramientas ni métodos usados.

== Ítem 2

Se identificaron las siguientes actividades a realizar:

* Buscar la forma de trabajar con datos ficticios mientras se obtiene información por parte de las entidades. Esto permitirá ir aplicando algunos procesos a realizar sobre la data real.
    * https://mockaroo.com[Mockaro]: generador de datos aleatorios.
    * Listado de datos abiertos compartido por Daniel.
* Buscar datos públicos y confiables que permitan complementar los datos entregados por las entidades elegidas.
* Establecer un plan de trabajo genérico, en donde se establezcan las actividades a realizar durante cada etapa, independiente del proyecto a ejecutar.
* Investigar sobre el uso de las herramientas que podríamos implementar en el proyecto: librerías de visualización, caracterización espacial, etc.

== Ítem 3

Se discute la posibilidad de abordar un proyecto externo, por fuera del listado de *Open Projects* provistos para *DS4A*, en caso de no obtener respuesta por parte de las entidades elegidas.

Luz Elena menciona a un conocido que tiene una iniciativa sin ánimo de lucro que busca aprovechar los datos de uso público para combatir la desinformación y mejorar la toma de decisiones por parte de las entidades públicas: https://chis.pa[Chispa].

Teniendo en cuenta esta nueva alternativa, se programa una reunión con el encargado para conocer algunos de los proyectos que se puedan ejecutar para el programa *DS4A*.

== Pasos Siguientes

. Realizar seguimiento a la comunicación enviada a las entidades seleccionadas del listado de Open Projects.
. Realizar reunión con el representante del proyecto *Chispa* y conocer las propuestas disponibles. Se programa para el 2020-05-31 a las 15:30.
. Crear un borrador del plan de trabajo genérico para el Practicum.
