*Fecha:* 2020-05-25

*Hora:* 15:00

== Participantes

* Daniel Gaitan Forero
* Fabio Andrés Sánchez Bernal
* Jhon Alexander Parra Jiménez
* Jonathan Guevara Agudelo
* Luz Elena Thompson Pinzón
* Maria Camila Manrique Nuñez

== Agenda

. Discutir la elección del proyecto final a partir del listado de *Open Projects* disponibles en la plataforma de *DS4A*.
. Pasos siguientes.

== Ítem 1

Cada miembro del equipo revisó los casos y de acuerdo con su percepción, selecionó 5 candidatos asignandoles una puntuación de 1 a 5 (1: menos relevante, 5: más relevante).

Se identificaron 3 proyectos con la mayor puntuación:

. Ministerio de Justicia
. Alcaldía de Copacabana
. EPM - 1

Los dos primeros destacaron por su componente social y el impacto positivo que tendría el desarrollo de cada proyecto, en especial el segundo, que podría generalizarse y aplicarse a otros entes territoriales.
El tercero destacó por su objetivo bien definido y la facilidad con la que se podría realizar el análisis de los datos disponibles.

Al realizar la discusión grupal de los proyectos, se identificó que podrían haber problemas en los dos primeros por contener en su mayoría datos categóricos.
Además, de que se podrían presentar inconvenientes al no contar con datos adicionales que permitan relacionar variables y hacer una análisis más detallado.

Se decide realizar una sesión adicional para tomar le decisión final sobre el proyecto a ejecutar.
Cada integrante deberá elegir, de la lista individual de candidatos inicial, uno que considere el más relevante (puntuación de 5) y deberá argumentar el porqué sería la opción más viable.

== Pasos Siguientes

. Se programa una nueva reunión el 2020-05-28 a las 17:00 para la elección final del proyecto.
